// <auto-generated />
using System;
using Kurdi.CleanCode.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kurdi.CleanCode.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221101114705_InitialModel")]
    partial class InitialModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kurdi.CleanCode.Core.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<double>("Salary")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Kurdi.CleanCode.Core.Entities.Language", b =>
                {
                    b.Property<string>("LanguageCode")
                        .HasColumnType("text")
                        .HasColumnName("language_code");

                    b.Property<string>("LanguageName")
                        .HasColumnType("text")
                        .HasColumnName("language_name");

                    b.HasKey("LanguageCode");

                    b.ToTable("languages");
                });

            modelBuilder.Entity("Kurdi.CleanCode.Core.Entities.Stock.StockItem", b =>
                {
                    b.Property<string>("Sku")
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<int>("SupplierIdentity")
                        .HasColumnType("integer")
                        .HasColumnName("supplier_identity");

                    b.HasKey("Sku");

                    b.ToTable("stock_items");
                });

            modelBuilder.Entity("Kurdi.CleanCode.Core.Entities.Stock.StockItemDetails", b =>
                {
                    b.Property<string>("LanguageCode")
                        .HasColumnType("text")
                        .HasColumnName("language_code");

                    b.Property<string>("Sku")
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("LanguageCode", "Sku");

                    b.HasIndex("Sku");

                    b.ToTable("stock_items_details");
                });

            modelBuilder.Entity("Kurdi.CleanCode.Core.Entities.Stock.StockItem", b =>
                {
                    b.OwnsOne("Kurdi.CleanCode.Core.Entities.Stock.StockItemPrices", "StockItemPrices", b1 =>
                        {
                            b1.Property<string>("StockItemSku")
                                .HasColumnType("text");

                            b1.Property<double>("CostPrice")
                                .HasColumnType("double precision")
                                .HasColumnName("cost_price");

                            b1.Property<double>("Discount")
                                .HasColumnType("double precision")
                                .HasColumnName("discount");

                            b1.Property<bool>("IsDiscounted")
                                .HasColumnType("boolean")
                                .HasColumnName("is_discounted");

                            b1.Property<double>("SellingPrice")
                                .HasColumnType("double precision")
                                .HasColumnName("selling_price");

                            b1.HasKey("StockItemSku");

                            b1.ToTable("stock_items");

                            b1.WithOwner()
                                .HasForeignKey("StockItemSku");
                        });

                    b.OwnsOne("Kurdi.CleanCode.Core.Entities.Stock.StockItemQuantity", "StockItemQuantity", b1 =>
                        {
                            b1.Property<string>("StockItemSku")
                                .HasColumnType("text");

                            b1.Property<int>("AvailableStock")
                                .HasColumnType("integer")
                                .HasColumnName("available_stock");

                            b1.Property<int>("ReservedStock")
                                .HasColumnType("integer")
                                .HasColumnName("reserved_stock");

                            b1.Property<int>("TotalStock")
                                .HasColumnType("integer")
                                .HasColumnName("total_stock");

                            b1.HasKey("StockItemSku");

                            b1.ToTable("stock_items");

                            b1.WithOwner()
                                .HasForeignKey("StockItemSku");
                        });

                    b.Navigation("StockItemPrices");

                    b.Navigation("StockItemQuantity");
                });

            modelBuilder.Entity("Kurdi.CleanCode.Core.Entities.Stock.StockItemDetails", b =>
                {
                    b.HasOne("Kurdi.CleanCode.Core.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kurdi.CleanCode.Core.Entities.Stock.StockItem", "StockItem")
                        .WithMany("StockItemDetails")
                        .HasForeignKey("Sku")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("StockItem");
                });

            modelBuilder.Entity("Kurdi.CleanCode.Core.Entities.Stock.StockItem", b =>
                {
                    b.Navigation("StockItemDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
